#%RAML 1.0
title: MuPro AM
version: 1
mediaType:  application/json
baseUri: http://{server}:{port}
baseUriParameters:
  server:
    description: The Server Running this
    example: 10.14.210.114
    required: true
    default: 10.14.210.114
  port:
    description: The Server Port
    example: 7878
    required: true
    default: 7878
protocols: [ HTTP ]
types:
  - Example:  !include example.schema.json
  - Examples:  !include examples.schema.json
/examples:
  displayName: Examples
  description: Get a List of Examples
  get:
    responses:
      200:
        body:
          application/json:
            type: Examples
            example: |
              [
                  {
                    "id":"01",
                    "name":"Soemthing"
                  },
                  {
                    "id":"02",
                    "name":"FooBar"
                  }
                ]
  post:
    body:
      application/json:
        type: Example
    responses:
      201:
        body:
          application/json:
            type: Example
  /{exampleID}:
    displayName: Example
    description: A Single Example Object
    uriParameters:
      exampleID:
        displayName: Example ID
        type: string
    put:
      body:
        application/json:
          type: Example
      responses:
        200:
          body:
            application/json:
              type: Example
    delete:
      responses:
        200: