@startuml
class ExampleController {
  {method} ExampleController ExampleController(path)
  {method} void getExample(id, callback)
  {method} void listExamples(callback)
  {method} void addExample(data, callback)
  {method} void updateExample(id, data, callback)
  {method} void deleteExample(id, callback)
}
@enduml